#%RAML 1.0 Library

types: 
  ContractDetailsType:
    properties: 
      contractType?: string
      hasMonthlySalary?: boolean
      hasHourlySalary?: boolean
      salaryRate?: number
      maxWorkingHours?: number
      minWorkingHours?: number
