#%RAML 1.0 Library

types: 
  WorkplaceType:
    properties: 
      name: string
      supervisorName: string
      email: string
      phone: string
      password: string
      address: 
        type: object
        properties: 
          street: string
          postalCode: string
          city: string
          country: string
  EditWorkplaceType:
    properties: 
      name?: string
      supervisorName?: string
      email?: string
      phone?: string
      password?: string
      address?: 
        type: object
        properties: 
          street: string
          postalCode: string
          city: string
          country: string
  RoleType:
    properties: 
      name: string